name: Main

on:
  push:
    branches:
      - main

jobs:
  start:
    runs-on: ubuntu-latest
    permissions:
      id-token: 'write'
    steps:
      - uses: actions/checkout@v2
      - id: 'auth'
        uses: google-github-actions/auth@v0.8.0
        with:
          workload_identity_provider: 'projects/381801417627/locations/global/workloadIdentityPools/bq-sandbox-20220730/providers/bq-sandbox-provider-20220730'
          service_account: bq-sandbox-worker@lacolaco-net.iam.gserviceaccount.com
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.node-version'
          cache: 'yarn'
      - run: yarn install --frozen-lockfile
      - name: Execute
        run: yarn start
