name: Main

on:
  push:
    branches:
      - main

jobs:
  exec:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@3
        with:
          node-version-file: '.node-version'
      - name: Execute
        run: npm run exec
